version: '3'

vars:
  BINARY_NAME: "shortener"
  MAIN: "./cmd/shortener"

  LOAD_SCRIPT_BINARY_NAME: "high-load"
  LOAD_SCRIPT_BINARY_PATH: "./cmd/scripts/high-load"

tasks:
  default:
    desc: "Собрать и сразу запустить с параметрами"
    deps:
      - build
    cmds:
      - '{{ .MAIN }}/{{ .BINARY_NAME }}'

  swag:
    desc: "Собрать и сразу запустить с параметрами"
    cmds:
      - swag init -g cmd/shortener/main.go

  build:
    desc: "Собрать бинарник"
    deps:
      - swag
    cmds:
      - go build -o {{.MAIN}} {{.MAIN}}

  b:
    desc: "Алиас для build"
    deps:
      - build

  test:
    desc: "Запустить unit-тесты"
    cmds:
      - go test -count=1 -v ./...

  t:
    desc: "Алиас для test"
    deps:
      - test

  lint:
    desc: "Форматирование"
    cmds:
      - gofmt -w .
      - goimports -w .

  linter:
    desc: "Запустить кастомный линтер noexit"
    cmds:
      - go build -o bin/linter.exe ./cmd/linter
      - ./bin/linter.exe ./...

  bench:
    desc: "Бенчмарки"
    cmds:
      - go test -bench . -benchmem

  godoc:
    desc: "Документация"
    cmds:
      - pkgsite -open

  high-load:
    desc: "100 000 запросов на создание"
    cmds:
      - go build -o {{.LOAD_SCRIPT_BINARY_PATH}} {{.LOAD_SCRIPT_BINARY_PATH}}
      - '{{ .LOAD_SCRIPT_BINARY_PATH }}/{{ .LOAD_SCRIPT_BINARY_NAME }}'
