// Code generated by reset tool. DO NOT EDIT.
//go:generate go run github.com/Alexey-zaliznuak/shortener/cmd/reset

package config

func (rs *AppConfig) Reset() {
	if rs == nil {
		return
	}

	rs.LoggingLevel = ""
	if resetter, ok := interface{}(&rs.DB).(interface{ Reset() }); ok {
		resetter.Reset()
	} else {
		rs.DB = DBConfig{}
	}
	if resetter, ok := interface{}(&rs.Auth).(interface{ Reset() }); ok {
		resetter.Reset()
	} else {
		rs.Auth = AuthConfig{}
	}
	rs.Audit.AuditURL = ""
	rs.Audit.AuditFile = ""
	rs.Server.BaseURL = ""
	rs.Server.Address = ""
	rs.Server.ShortLinksLength = 0
}
